using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;

public class DebugInfo : MonoBehaviour
{ 
    [SerializeField] private TMP_Text flRpmLabel;
    [SerializeField] private TMP_Text frRpmLabel;
    [SerializeField] private TMP_Text rlRpmLabel;
    [SerializeField] private TMP_Text rrRpmLabel;

    public void setRpmLabels(float flRpm, float frRpm, float rlRpm, float rrRpm){
        flRpmLabel.text = flRpm.ToString();
        frRpmLabel.text = frRpm.ToString();
        rlRpmLabel.text = rlRpm.ToString();
        rrRpmLabel.text = rrRpm.ToString();
    }
}
